#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Poop Drive -                                        *|
|*                                          POOPY on Tetrix                                               *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                         POOP CONFIGURATION                                             *|
|*    POOPS:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [P/OO Port]             [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/

#include "JoystickDriver.c"

task main()
{
	servo[servo1] = 240;
	servo[servo2] = 234;
	servo[servo3] = 110;
	servo[servo4] = 100;
  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);
    if (joy1Btn(1)) {
    	servoChangeRate[servo1] = 1;
    	servo[servo1] = 120;
  	} else if (joy1Btn(2)) {
  		servoChangeRate[servo1] = 0;
    	servo[servo1] = 240;
    }
    if (joy1Btn(6)) {
    	servo[servo4] = 220;
  	} else if (joy1Btn(8)) {
    	servo[servo4] = 110;
    }
   	int threshold = 20;

		if (abs(joystick.joy1_y2)>threshold){
    	motor[motorD] = joystick.joy1_y2/4;
  	}
  	else {
  		motor[motorD] = 0;
  	}

  	if (abs(joystick.joy1_y1)>threshold){
    	motor[motorE] = joystick.joy1_y1/4;
  	}
  	else {
  		motor[motorE] = 0;
  	}
  }
}
