#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motor_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor_3,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motor_4,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-gyro.h"

task main() {
	servo[servo1] = 240;
	servo[servo2] = 234;
	servo[servo3] = 110;
	servo[servo4] = 100;

	while(true) {
		getJoystickSettings(joystick);
		int threshold = 25;
				if(abs(joystick.joy1_y1) >threshold) { // left wheel set
		   motor[motor_1] = joystick.joy1_y1/3;
	     motor[motor_2] = joystick.joy1_y1/3;
		} else if(joystick.joy1_TopHat == 2) { // left strafe (right analog stick)
			motor[motor_1] = -100;
	    motor[motor_2] = 100;
	  }	else if(joystick.joy1_TopHat == 6) { // right strafe (right analog stick)
		   motor[motor_1] = 100;
	     motor[motor_2] = -100;
		} else {
			 motor[motor_1] = 0;
	     motor[motor_2] = 0;
		}
		if(abs(joystick.joy1_y2) > threshold) {	// right wheel set
			motor[motor_3] = joystick.joy1_y2/3;
	    motor[motor_4] = joystick.joy1_y2/3;
		} else if(joystick.joy1_TopHat == 2) {	// left strafe (left analog stick)
			 motor[motor_3] = 100;
	     motor[motor_4] = -100;
		} else if(joystick.joy1_TopHat == 6) { // right strafe (left analog stick)
			 motor[motor_3] = -100;
	     motor[motor_4] = 100;
		} else {
			 motor[motor_3] = 0;
	     motor[motor_4] = 0;
		}

		if (joy2Btn(1)) {
    	servoChangeRate[servo1] = 0;
    	servo[servo1] = 120;
  	} else if (joy2Btn(2)) {
  		servoChangeRate[servo1] = 0;
    	servo[servo1] = 240;
    }
    if (joy2Btn(6)) {
    	servo[servo4] = 224;
  	} else if (joy2Btn(8)) {
    	servo[servo4] = 155;
    }

		if (abs(joystick.joy2_y2)>threshold){
    	motor[motorH] = joystick.joy2_y2/4;
  	}
  	else {
  		motor[motorH] = 0;
  	}

  	if (abs(joystick.joy2_y1)>threshold){
    	motor[motorI] = joystick.joy2_y1/4;
  	}
  	else {
  		motor[motorI] = 0;
  	}
  }
}
