#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motor_4,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor_3,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor_2,       tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-gyro.h"

#define X_STICK joystick.joy1_x1
#define Y_STICK joystick.joy1_y1
#define Z_STICK joystick.joy1_x2

void initializeRobot()
{
	servoChangeRate[servo2] = 4;
	servo[servo1] = 230;
	servo[servo2] = 0;
	servo[servo3] = 125;
	servo[servo4] = 90;
  return;
}

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase
  ClearTimer(T1);
  while (true)
  {
	  getJoystickSettings(joystick);
    if (joy1Btn(1) == 1) {
    	servo[servo2] = 0;
  	}
  	else if (joy1Btn(2) == 1) {
    	servo[servo2] = 220;
    } else servo[servo2] = ServoValue[servo2];
  	if (joy1Btn(3) == 1) {
  		motor[motorA] = 40;
  		servo[servo1] = 145;
		}	else motor[motorA] = 0;
		if (joy1Btn(6) == 1) {
  		servo[servo1] = 175;
  		motor[motorA] = -70;
		} else motor[motorA] = 0;
		if (joy1Btn(10) == 1) {
			servo[servo3] = 210;
			servo[servo4] = 240;
		} else {
			servo[servo3] = 125;
		}

    int threshold = 25;
    int xAxis = 0;
    int yAxis = 0;
    int zAxis = 0;

    if(abs(X_STICK) > threshold)
    {
    	if(abs(X_STICK) > 123) xAxis = -X_STICK;
    	else xAxis = -X_STICK/3;
    } else xAxis = 0;
    //---------------------------------------------------------------------------
    if(abs(Y_STICK) > threshold)
    {
    	if(abs(Y_STICK) > 123) yAxis = Y_STICK;
    	else yAxis = Y_STICK/3;
    } else yAxis = 0;
    //---------------------------------------------------------------------------
    if(abs(Z_STICK) > 50)
    {
    	if(abs(Z_STICK) > 123) zAxis = -Z_STICK;
    	else zAxis = -Z_STICK/4;
    } else zAxis = 0;
    if(joystick.joy1_TopHat == -1) {
		  int motor1 = 0;

		  motor1 = xAxis;
		  motor1 = yAxis+motor1;
		  motor1 = (-zAxis)+motor1;

		  motor[motor_1] = motor1;

		  //-------------------------------------------------------------

		  int motor2 = 0;

		  motor2 = -xAxis;
		  motor2 = yAxis+motor2;
		  motor2 = zAxis+motor2;

		  motor[motor_2] = motor2;

		  //-------------------------------------------------------------

		  int motor3 = 0;

		  motor3 = -xAxis;
		  motor3 = (-yAxis)+motor3;
		  motor3 = (-zAxis)+motor3;

		  motor[motor_3] = motor3;

		  //-------------------------------------------------------------

		  int motor4 = 0;

		  motor4 = xAxis;
		  motor4 = (-yAxis)+motor4;
		  motor4 = zAxis+motor4;

		  motor[motor_4] = motor4;


			} else if(joystick.joy1_TopHat == 2) {
				if (SensorValue[sonarSensor] < 15) {
					motor[motor_1] = 0;
	    		motor[motor_2] = 0;
	    		motor[motor_3] = 0;
	    		motor[motor_4] = 0;
	    	} else {
				  motor[motor_1] = -20;
	    		motor[motor_2] = 20;
	    		motor[motor_3] = 20;
	    		motor[motor_4] = -20;
	    	}
			} else if(joystick.joy1_TopHat == 6) {
			  if (SensorValue[sonarSensor] < 15) {
					motor[motor_1] = 0;
	    		motor[motor_2] = 0;
	    		motor[motor_3] = 0;
	    		motor[motor_4] = 0;
	    	} else {
				  motor[motor_1] = 20;
	    		motor[motor_2] = -20;
	    		motor[motor_3] = -20;
	    		motor[motor_4] = 20;
	    	}
		}
  }
}
